---
- name: Include installation on OS family
  include: "install.{{ ansible_os_family | lower }}.yml"

# This role installs and sets up keepalived
- name: Copy keepalived systemd service file
  copy: 
    src: keepalived.service
    dest: /etc/systemd/system/keepalived.service
    mode: 0644
    owner: root
    group: root
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
  tags: keepalived

- name: Copy health check script
  template: 
    src: {{ item.1.filename }}.j2 
    dest: "{{ item.1.path }}/{{ item.1.filename }}"
    mode: 0755
  tags: keepalived
  with_subelements:
    - "{{ keepalived_vrrp_instances }}"
    - scripts

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service:
    name: keepalived
    state: started
  tags: keepalived

- name: Disable keepalived service
  service: 
    name: keepalived
    enabled: no
  tags: keepalived
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04' or
        ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Ensure systemd is reloaded if keepalived service has changed
  command: systemctl daemon-reload
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04' or
        ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Enable keepalived service
  service: 
    name: keepalived
    enabled: yes
  tags: keepalived
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04' or
        ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
